Gary Chen\
IST-652\
Homework 1: Structured Data\
Date: 8/8/2921


**Data:**

We'll be analyzing the Ramen-Rating data set.

This Data set was found on Kaggle:[Ramen-Rating Link](https://www.kaggle.com/residentmario/ramen-ratings)

The original file has 2580 rows and 7 columns.

**Questions:**

Which country has the strongest Ramen culture in terms of popularity, rating, brand, and variety?
    
    - Which country has the most 5.0 stars rated ramens?
            Japan          74
            Malaysia       54
            Taiwan         48
            South Korea    44
            Singapore      36
        
    - Which Country and Brand has the most ramen variety?
   
            Nissin         381
            Nongshim        98
            Maruchan        76
            Mama            71
            Paldo           66
            
            Japan            352
            USA              323
            South Korea      309
            Taiwan           224
            Thailand         191
    
    
    - Which countries had the most ramen variety with top 10 awards?
            Singapore      7
            Malaysia       6
            Japan          6
            South Korea    5
            Indonesia      4
            Thailand       3
            Taiwan         2
            China          1
            Hong Kong      1
            Myanmar        1
            USA            1
            
    - For each country, what're the highest rated ramen?
        Please see in cell In[24]
    
What're the top 10 best rated ramens based on ratings and popularity? 

    - Which style of ramen was most popular and best rated?
            
            Pack    576
            Cup     222
            Bowl    176
            Tray     20
            Box       4
            Can       1
            Bar       1
    
    - Which contry had to the most in top 1000 Ramen Scores? 
            
            Japan            159
            Malaysia         108
            Taiwan            87
            Hong Kong         82
            USA               79

In [1]:
import pandas as pd

ramen_file = 'ramen-ratings.csv' #path for ramen-ratings.csv

#Read Ramen file into dataframe, csv = comma as the separator 

ramen_df = pd.read_csv(ramen_file, sep=',')
ramen_df.shape

(2580, 7)

In [2]:
#show Ramen columns
ramen_df.columns.values.tolist()

['Review #', 'Brand', 'Variety', 'Style', 'Country', 'Stars', 'Top Ten']

In [3]:
#top 5 rows of ramen df
ramen_df.head()

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN

In [4]:
#get descriptive statistics from numeric columns

reviews = ramen_df['Review #']
stars = ramen_df['Stars']

print(reviews.describe())

print('\n')

print(stars.describe())

#not getting full descriptive statistics on Stars column - dtype: object

count    2580.000000
mean     1290.500000
std       744.926171
min         1.000000
25%       645.750000
50%      1290.500000
75%      1935.250000
max      2580.000000
Name: Review #, dtype: float64


count     2580
unique      51
top          4
freq       384
Name: Stars, dtype: object

In [5]:
#check distinct values for stars column
unique_star = stars.unique()
print(unique_star)

['3.75' '1' '2.25' '2.75' '4.75' '4' '0.25' '2.5' '5' '4.25' '4.5' '3.5'
 'Unrated' '1.5' '3.25' '2' '0' '3' '0.5' '4.00' '5.0' '3.50' '3.8' '4.3'
 '2.3' '5.00' '3.3' '4.0' '3.00' '1.75' '3.0' '4.50' '0.75' '1.25' '1.1'
 '2.1' '0.9' '3.1' '4.125' '3.125' '2.125' '2.9' '0.1' '2.8' '3.7' '3.4'
 '3.6' '2.85' '3.2' '3.65' '1.8']

In [6]:
#Found 'Unrated' which is not a int or float
#convert 'Unrated' to 0.001 to designate as Unrated
#This will allow us to do calculations with the 'Stars' column
ramen_df.loc[ramen_df['Stars'] == 'Unrated', "Stars"] = 0.001

print(ramen_df['Stars'])
print('\n')

#convert Stars column to numeric to do calculations
ramen_df['Stars'] = pd.to_numeric(ramen_df['Stars'])

#summary stats for 'Stars' column
print(ramen_df['Stars'].describe())

0       3.75
1          1
2       2.25
3       2.75
4       3.75
        ...
2575     3.5
2576       1
2577       2
2578       2
2579     0.5
Name: Stars, Length: 2580, dtype: object


count    2580.000000
mean        3.650428
std         1.022354
min         0.000000
25%         3.250000
50%         3.750000
75%         4.250000
max         5.000000
Name: Stars, dtype: float64

In [7]:
#get top Brand

unique_brand = ramen_df['Brand'].value_counts()
print(unique_brand)

#number of unique ramen brands 
print('Number of unique brands : ', len(unique_brand))

#Nissin has by far the most ramen varieties

Nissin         381
Nongshim        98
Maruchan        76
Mama            71
Paldo           66
              ...
Right Foods      1
Tayho            1
O Sung           1
Springlife       1
Daraz            1
Name: Brand, Length: 355, dtype: int64
Number of unique brands :  355

In [8]:
#get rating distribution 
unique_rating = ramen_df['Stars'].value_counts()

print(unique_rating)
#There were 3 Unrated Ramen out of 2580 ramens, 0.001 has 3 values

print('\n')


print('Number of unique ratings : ', len(unique_rating))

4.000    393
5.000    386
3.750    350
3.500    335
3.000    176
3.250    170
4.250    143
4.500    135
2.750     85
2.000     68
2.500     67
4.750     64
1.500     37
1.750     27
1.000     26
0.000     26
2.250     21
0.500     14
0.250     11
1.250     10
4.300      4
3.800      3
0.001      3
1.100      2
2.900      2
2.300      2
4.125      2
3.100      2
2.800      2
3.700      1
2.100      1
3.400      1
3.300      1
1.800      1
0.750      1
2.125      1
3.600      1
0.100      1
0.900      1
3.125      1
2.850      1
3.650      1
3.200      1
Name: Stars, dtype: int64


Number of unique ratings :  43

In [9]:
#counts for how many ramen varities for each country
unique_country = ramen_df['Country'].value_counts()

#Which countries has the most Ramen variety?
print(unique_country)

print('\n')

print('Number of unique countries : ', len(unique_country))

#Japan, USA, and South Korea have the most varities

Japan            352
USA              323
South Korea      309
Taiwan           224
Thailand         191
China            169
Malaysia         156
Hong Kong        137
Indonesia        126
Singapore        109
Vietnam          108
UK                69
Philippines       47
Canada            41
India             31
Germany           27
Mexico            25
Australia         22
Netherlands       15
Nepal             14
Myanmar           14
Hungary            9
Pakistan           9
Bangladesh         7
Colombia           6
Cambodia           5
Brazil             5
Fiji               4
Holland            4
Poland             4
Sarawak            3
Finland            3
Sweden             3
Dubai              3
Ghana              2
Estonia            2
United States      1
Nigeria            1
Name: Country, dtype: int64


Number of unique countries :  38

In [10]:
#Which Brand Has the most Variety? 
unique_brand = ramen_df['Brand'].value_counts()

print(unique_brand)

print('\n')

print('Number of unique brand : ', len(unique_country))

print('\n')

#what are the top 10 Brands with the most Variety
print(unique_brand.head(10))

Nissin         381
Nongshim        98
Maruchan        76
Mama            71
Paldo           66
              ...
Right Foods      1
Tayho            1
O Sung           1
Springlife       1
Daraz            1
Name: Brand, Length: 355, dtype: int64


Number of unique brand :  38


Nissin           381
Nongshim          98
Maruchan          76
Mama              71
Paldo             66
Myojo             63
Indomie           53
Samyang Foods     52
Ottogi            46
Lucky Me!         34
Name: Brand, dtype: int64

In [11]:
#Which country has the most 5.0 stars rated ramens?

#first create a new ramen df with only 5.0 stars
Ramen_5stars = ramen_df[ramen_df['Stars'] == 5.000]
display(Ramen_5stars)

print('\n')

#do the value counts number of 5 stars by country
print(Ramen_5stars['Country'].value_counts())

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
10,2570,Tao Kae Noi,Creamy tom Yum Kung Flavour,Pack,Thailand,5.0,NaN
11,2569,Yamachan,Yokohama Tonkotsu Shoyu,Pack,USA,5.0,NaN
14,2566,Nissin,Demae Ramen Bar Noodle Aka Tonkotsu Flavour In...,Pack,Hong Kong,5.0,NaN
17,2563,Yamachan,Tokyo Shoyu Ramen,Pack,USA,5.0,NaN
21,2559,Jackpot Teriyaki,Beef Ramen,Pack,USA,5.0,NaN
...,...,...,...,...,...,...,...
2530,50,Indomie,Mi Goreng,Pack,Indonesia,5.0,NaN
2533,47,Indomie,Mi Goreng Jumbo Barbecue Chicken,Pack,Indonesia,5.0,2012 #2
2535,45,Indomie,Mi Goreng Sate,Pack,Indonesia,5.0,\n
2552,28,Nissin,Chikin Ramen,Pack,Japan,5.0,NaN
2567,13,Sapporo Ichiban,Chow Mein,Pack,Japan,5.0,2012 #4

Japan          74
Malaysia       54
Taiwan         48
South Korea    44
Singapore      36
USA            31
Indonesia      23
Hong Kong      22
Thailand       19
China          12
UK              4
Myanmar         4
Philippines     2
Cambodia        2
Canada          2
India           2
Germany         1
Sarawak         1
Mexico          1
Vietnam         1
Nepal           1
Brazil          1
Australia       1
Name: Country, dtype: int64

In [12]:
#check for NULL values for Top Ten 

ramen_df[ramen_df['Top Ten'].isnull()]

ramen_df['Top Ten'].isnull()

0       True
1       True
2       True
3       True
4       True
        ...
2575    True
2576    True
2577    True
2578    True
2579    True
Name: Top Ten, Length: 2580, dtype: bool

In [13]:
#update Top Ten NUlL values to no 
ramen_df.loc[ramen_df['Top Ten'].isnull(), 'Top Ten'] = 'no'

ramen_df.head()

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,no
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1.00,no
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,no
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,no
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,no

In [25]:
#create 'Ramen Score' column based on Review #, Stars, & Top Ten flag

#first create a 'Top Ten points score column - If Ramen was rated top ten of a year, 500 points. If not, 0 points.
#This will give a yearly top 10 rated Ramen extra 500 pts to be calculated in our 'Ramen Score'
#500 extra pts was caculated by a Top Ten award should equal an additional 100 reviews of 5 stars
#We will not scale down these 100 reviews like we will do later
#This will add 500 pts to a yearly Top Ten awarded Ramen's Score

#import numpy to use where function
import numpy as np

#check all Top Ten values that do not equal to no
display(ramen_df[ramen_df['Top Ten'] != 'no'])

print('\n')

#there are some 'Top Ten' values as \n. We can replace that with no. I don't think '\n' denotes as Top Ten ramen

#update Top Ten '\n' values with no
ramen_df.loc[ramen_df['Top Ten'] == '\n', 'Top Ten'] = 'no'
#display & check Top Ten values ago 
display(ramen_df[ramen_df['Top Ten'] != 'no'])

#create df fir awarded ramen
awarded_ramen = ramen_df[ramen_df['Top Ten'] != 'no']

#caclulate countries with top 
display(awarded_ramen['Country'].value_counts())

print('\n')

#use numpy where function to create 'Top Ten - extra pts' columns based on the condition
ramen_df['Top Ten - extra pts'] = np.where(ramen_df['Top Ten'] != 'no', 500, 0)

#check if Top Ten rated has been awarded the extra pts
display(ramen_df[ramen_df['Top Ten'] != 'no'])

,Review #,Brand,Variety,Style,Country,Stars,Top Ten,Top Ten - extra pts,Ramen Score
616,1964,MAMA,Instant Noodles Coconut Milk Flavour,Pack,Myanmar,5.00,2016 #10,500,2293.607306
633,1947,Prima Taste,Singapore Laksa Wholegrain La Mian,Pack,Singapore,5.00,2016 #1,500,2278.082192
655,1925,Prima,Juzz's Mee Creamy Chicken Flavour,Pack,Singapore,5.00,2016 #8,500,2257.990868
673,1907,Prima Taste,Singapore Curry Wholegrain La Mian,Pack,Singapore,5.00,2016 #5,500,2241.552511
752,1828,Tseng Noodles,Scallion With Sichuan Pepper Flavor,Pack,Taiwan,5.00,2016 #9,500,2169.406393
891,1689,Wugudaochang,Tomato Beef Brisket Flavor Purple Potato Noodle,Pack,China,5.00,2016 #7,500,2042.465753
942,1638,A-Sha Dry Noodle,Veggie Noodle Tomato Noodle With Vine Ripened ...,Pack,Taiwan,5.00,2015 #10,500,1995.890411
963,1617,MyKuali,Penang Hokkien Prawn Noodle (New Improved Taste),Pack,Malaysia,5.00,2015 #7,500,1976.712329
995,1585,CarJEN,Nyonya Curry Laksa,Pack,Malaysia,5.00,2015 #4,500,1947.488584
1059,1521,Maruchan,Gotsumori Sauce Yakisoba,Tray,Japan,5.00,2015 #9,500,1889.041096
1072,1508,Mamee,Chef Gold Recipe Mi Kari Seribu Rasa,Pack,Malaysia,5.00,2015 #6,500,1877.168950
1080,1500,MyKuali,Penang Red Tom Yum Goong Noodle,Pack,Malaysia,5.00,2015 #1,500,1869.863014
1109,1471,Mama,Instant Noodles Shrimp Creamy Tom Yum Flavour ...,Pack,Thailand,5.00,2013 #10,500,1843.378995
1114,1466,Mama,Oriental Style Instant Noodles Green Curry Fla...,Pack,Thailand,5.00,2015 #8,500,1838.812785
1230,1350,Mamee,Chef Curry Laksa Flavour,Pack,Malaysia,5.00,2014 #7,500,1732.876712
1250,1330,Sapporo Ichiban,Otafuku Okonomi Sauce Yakisoba,Tray,Japan,5.00,2014 #4,500,1714.611872
1272,1308,Nongshim,Soon Veggie Noodle Soup,Pack,South Korea,5.00,2014 #9,500,1694.520548
1278,1302,Mama,Instant Noodles Yentafo Tom Yum Mohfai Flavour,Pack,Thailand,5.00,2014 #10,500,1689.041096
1309,1271,Prima Taste,Singapore Chilli Crab La Mian,Pack,Singapore,5.00,2014 #8,500,1660.730594
1382,1198,Samyang Foods,Maesaengyitangmyun Baked Noodle,Pack,South Korea,5.00,2014 #5,500,1594.063927
1397,1183,Paldo,Cheese Noodle,Pack,South Korea,5.00,2014 #6,500,1580.365297
1493,1087,MyKuali,Penang White Curry Noodle,Pack,Malaysia,5.00,2014 #1,500,1492.694064
1588,992,Prima Taste,Singapore Laksa La Mian,Pack,Singapore,5.00,2013 #1,500,1405.936073
1589,991,Prima Taste,Singapore Curry La Mian,Pack,Singapore,5.00,2013 #2,500,1405.022831
1646,934,Nongshim,Jinjja Jinjja Flamin' Hot & Nutty,Pack,USA,5.00,2013 #4,500,1352.968037
1757,823,Paldo,Kokomen Spicy Chicken,Pack,South Korea,5.00,2013 #9,500,1251.598174
1865,715,Indomie,Mi Goreng Rendang (Import),Pack,Indonesia,5.00,2013 #3,500,1152.968037
1972,608,Koka,Spicy Black Pepper,Pack,Singapore,5.00,2012 #10,500,1055.251142
2002,578,Nongshim,Shin Ramyun Black,Pack,South Korea,4.75,2012 #7,500,1001.461187
2146,434,Mi Sedaap,Kari Spesial,Pack,Indonesia,4.50,2012 #5,500,856.712329
2188,392,Nissin,Yakisoba Noodles Karashi,Tray,Japan,5.00,2012 #3,500,857.990868
2189,391,Myojo,Hyoubanya No Chukasoba Oriental,Pack,Japan,4.25,2012 #6,500,803.515982
2295,285,Doll,Artificial Chicken,Pack,Hong Kong,4.50,2012 #9,500,734.246575
2475,105,Indomie,Special Fried Curly Noodle,Pack,Indonesia,5.00,2012 #1,500,595.890411
2533,47,Indomie,Mi Goreng Jumbo Barbecue Chicken,Pack,Indonesia,5.00,2012 #2,500,542.922374
2549,31,Myojo,Ippeichan Yakisoba,Tray,Japan,4.00,2013 #6,500,522.648402
2567,13,Sapporo Ichiban,Chow Mein,Pack,Japan,5.00,2012 #4,500,511.872146

,Review #,Brand,Variety,Style,Country,Stars,Top Ten,Top Ten - extra pts,Ramen Score
616,1964,MAMA,Instant Noodles Coconut Milk Flavour,Pack,Myanmar,5.00,2016 #10,500,2293.607306
633,1947,Prima Taste,Singapore Laksa Wholegrain La Mian,Pack,Singapore,5.00,2016 #1,500,2278.082192
655,1925,Prima,Juzz's Mee Creamy Chicken Flavour,Pack,Singapore,5.00,2016 #8,500,2257.990868
673,1907,Prima Taste,Singapore Curry Wholegrain La Mian,Pack,Singapore,5.00,2016 #5,500,2241.552511
752,1828,Tseng Noodles,Scallion With Sichuan Pepper Flavor,Pack,Taiwan,5.00,2016 #9,500,2169.406393
891,1689,Wugudaochang,Tomato Beef Brisket Flavor Purple Potato Noodle,Pack,China,5.00,2016 #7,500,2042.465753
942,1638,A-Sha Dry Noodle,Veggie Noodle Tomato Noodle With Vine Ripened ...,Pack,Taiwan,5.00,2015 #10,500,1995.890411
963,1617,MyKuali,Penang Hokkien Prawn Noodle (New Improved Taste),Pack,Malaysia,5.00,2015 #7,500,1976.712329
995,1585,CarJEN,Nyonya Curry Laksa,Pack,Malaysia,5.00,2015 #4,500,1947.488584
1059,1521,Maruchan,Gotsumori Sauce Yakisoba,Tray,Japan,5.00,2015 #9,500,1889.041096
1072,1508,Mamee,Chef Gold Recipe Mi Kari Seribu Rasa,Pack,Malaysia,5.00,2015 #6,500,1877.168950
1080,1500,MyKuali,Penang Red Tom Yum Goong Noodle,Pack,Malaysia,5.00,2015 #1,500,1869.863014
1109,1471,Mama,Instant Noodles Shrimp Creamy Tom Yum Flavour ...,Pack,Thailand,5.00,2013 #10,500,1843.378995
1114,1466,Mama,Oriental Style Instant Noodles Green Curry Fla...,Pack,Thailand,5.00,2015 #8,500,1838.812785
1230,1350,Mamee,Chef Curry Laksa Flavour,Pack,Malaysia,5.00,2014 #7,500,1732.876712
1250,1330,Sapporo Ichiban,Otafuku Okonomi Sauce Yakisoba,Tray,Japan,5.00,2014 #4,500,1714.611872
1272,1308,Nongshim,Soon Veggie Noodle Soup,Pack,South Korea,5.00,2014 #9,500,1694.520548
1278,1302,Mama,Instant Noodles Yentafo Tom Yum Mohfai Flavour,Pack,Thailand,5.00,2014 #10,500,1689.041096
1309,1271,Prima Taste,Singapore Chilli Crab La Mian,Pack,Singapore,5.00,2014 #8,500,1660.730594
1382,1198,Samyang Foods,Maesaengyitangmyun Baked Noodle,Pack,South Korea,5.00,2014 #5,500,1594.063927
1397,1183,Paldo,Cheese Noodle,Pack,South Korea,5.00,2014 #6,500,1580.365297
1493,1087,MyKuali,Penang White Curry Noodle,Pack,Malaysia,5.00,2014 #1,500,1492.694064
1588,992,Prima Taste,Singapore Laksa La Mian,Pack,Singapore,5.00,2013 #1,500,1405.936073
1589,991,Prima Taste,Singapore Curry La Mian,Pack,Singapore,5.00,2013 #2,500,1405.022831
1646,934,Nongshim,Jinjja Jinjja Flamin' Hot & Nutty,Pack,USA,5.00,2013 #4,500,1352.968037
1757,823,Paldo,Kokomen Spicy Chicken,Pack,South Korea,5.00,2013 #9,500,1251.598174
1865,715,Indomie,Mi Goreng Rendang (Import),Pack,Indonesia,5.00,2013 #3,500,1152.968037
1972,608,Koka,Spicy Black Pepper,Pack,Singapore,5.00,2012 #10,500,1055.251142
2002,578,Nongshim,Shin Ramyun Black,Pack,South Korea,4.75,2012 #7,500,1001.461187
2146,434,Mi Sedaap,Kari Spesial,Pack,Indonesia,4.50,2012 #5,500,856.712329
2188,392,Nissin,Yakisoba Noodles Karashi,Tray,Japan,5.00,2012 #3,500,857.990868
2189,391,Myojo,Hyoubanya No Chukasoba Oriental,Pack,Japan,4.25,2012 #6,500,803.515982
2295,285,Doll,Artificial Chicken,Pack,Hong Kong,4.50,2012 #9,500,734.246575
2475,105,Indomie,Special Fried Curly Noodle,Pack,Indonesia,5.00,2012 #1,500,595.890411
2533,47,Indomie,Mi Goreng Jumbo Barbecue Chicken,Pack,Indonesia,5.00,2012 #2,500,542.922374
2549,31,Myojo,Ippeichan Yakisoba,Tray,Japan,4.00,2013 #6,500,522.648402
2567,13,Sapporo Ichiban,Chow Mein,Pack,Japan,5.00,2012 #4,500,511.872146

Singapore      7
Malaysia       6
Japan          6
South Korea    5
Indonesia      4
Thailand       3
Taiwan         2
China          1
Hong Kong      1
Myanmar        1
USA            1
Name: Country, dtype: int64

,Review #,Brand,Variety,Style,Country,Stars,Top Ten,Top Ten - extra pts,Ramen Score
616,1964,MAMA,Instant Noodles Coconut Milk Flavour,Pack,Myanmar,5.00,2016 #10,500,2293.607306
633,1947,Prima Taste,Singapore Laksa Wholegrain La Mian,Pack,Singapore,5.00,2016 #1,500,2278.082192
655,1925,Prima,Juzz's Mee Creamy Chicken Flavour,Pack,Singapore,5.00,2016 #8,500,2257.990868
673,1907,Prima Taste,Singapore Curry Wholegrain La Mian,Pack,Singapore,5.00,2016 #5,500,2241.552511
752,1828,Tseng Noodles,Scallion With Sichuan Pepper Flavor,Pack,Taiwan,5.00,2016 #9,500,2169.406393
891,1689,Wugudaochang,Tomato Beef Brisket Flavor Purple Potato Noodle,Pack,China,5.00,2016 #7,500,2042.465753
942,1638,A-Sha Dry Noodle,Veggie Noodle Tomato Noodle With Vine Ripened ...,Pack,Taiwan,5.00,2015 #10,500,1995.890411
963,1617,MyKuali,Penang Hokkien Prawn Noodle (New Improved Taste),Pack,Malaysia,5.00,2015 #7,500,1976.712329
995,1585,CarJEN,Nyonya Curry Laksa,Pack,Malaysia,5.00,2015 #4,500,1947.488584
1059,1521,Maruchan,Gotsumori Sauce Yakisoba,Tray,Japan,5.00,2015 #9,500,1889.041096
1072,1508,Mamee,Chef Gold Recipe Mi Kari Seribu Rasa,Pack,Malaysia,5.00,2015 #6,500,1877.168950
1080,1500,MyKuali,Penang Red Tom Yum Goong Noodle,Pack,Malaysia,5.00,2015 #1,500,1869.863014
1109,1471,Mama,Instant Noodles Shrimp Creamy Tom Yum Flavour ...,Pack,Thailand,5.00,2013 #10,500,1843.378995
1114,1466,Mama,Oriental Style Instant Noodles Green Curry Fla...,Pack,Thailand,5.00,2015 #8,500,1838.812785
1230,1350,Mamee,Chef Curry Laksa Flavour,Pack,Malaysia,5.00,2014 #7,500,1732.876712
1250,1330,Sapporo Ichiban,Otafuku Okonomi Sauce Yakisoba,Tray,Japan,5.00,2014 #4,500,1714.611872
1272,1308,Nongshim,Soon Veggie Noodle Soup,Pack,South Korea,5.00,2014 #9,500,1694.520548
1278,1302,Mama,Instant Noodles Yentafo Tom Yum Mohfai Flavour,Pack,Thailand,5.00,2014 #10,500,1689.041096
1309,1271,Prima Taste,Singapore Chilli Crab La Mian,Pack,Singapore,5.00,2014 #8,500,1660.730594
1382,1198,Samyang Foods,Maesaengyitangmyun Baked Noodle,Pack,South Korea,5.00,2014 #5,500,1594.063927
1397,1183,Paldo,Cheese Noodle,Pack,South Korea,5.00,2014 #6,500,1580.365297
1493,1087,MyKuali,Penang White Curry Noodle,Pack,Malaysia,5.00,2014 #1,500,1492.694064
1588,992,Prima Taste,Singapore Laksa La Mian,Pack,Singapore,5.00,2013 #1,500,1405.936073
1589,991,Prima Taste,Singapore Curry La Mian,Pack,Singapore,5.00,2013 #2,500,1405.022831
1646,934,Nongshim,Jinjja Jinjja Flamin' Hot & Nutty,Pack,USA,5.00,2013 #4,500,1352.968037
1757,823,Paldo,Kokomen Spicy Chicken,Pack,South Korea,5.00,2013 #9,500,1251.598174
1865,715,Indomie,Mi Goreng Rendang (Import),Pack,Indonesia,5.00,2013 #3,500,1152.968037
1972,608,Koka,Spicy Black Pepper,Pack,Singapore,5.00,2012 #10,500,1055.251142
2002,578,Nongshim,Shin Ramyun Black,Pack,South Korea,4.75,2012 #7,500,1001.461187
2146,434,Mi Sedaap,Kari Spesial,Pack,Indonesia,4.50,2012 #5,500,856.712329
2188,392,Nissin,Yakisoba Noodles Karashi,Tray,Japan,5.00,2012 #3,500,857.990868
2189,391,Myojo,Hyoubanya No Chukasoba Oriental,Pack,Japan,4.25,2012 #6,500,803.515982
2295,285,Doll,Artificial Chicken,Pack,Hong Kong,4.50,2012 #9,500,734.246575
2475,105,Indomie,Special Fried Curly Noodle,Pack,Indonesia,5.00,2012 #1,500,595.890411
2533,47,Indomie,Mi Goreng Jumbo Barbecue Chicken,Pack,Indonesia,5.00,2012 #2,500,542.922374
2549,31,Myojo,Ippeichan Yakisoba,Tray,Japan,4.00,2013 #6,500,522.648402
2567,13,Sapporo Ichiban,Chow Mein,Pack,Japan,5.00,2012 #4,500,511.872146

In [15]:
#view if Top Ten Ramen that have been appointed extra pts

ramen_df[ramen_df['Top Ten'] != 'no']

,Review #,Brand,Variety,Style,Country,Stars,Top Ten,Top Ten - extra pts
616,1964,MAMA,Instant Noodles Coconut Milk Flavour,Pack,Myanmar,5.00,2016 #10,500
633,1947,Prima Taste,Singapore Laksa Wholegrain La Mian,Pack,Singapore,5.00,2016 #1,500
655,1925,Prima,Juzz's Mee Creamy Chicken Flavour,Pack,Singapore,5.00,2016 #8,500
673,1907,Prima Taste,Singapore Curry Wholegrain La Mian,Pack,Singapore,5.00,2016 #5,500
752,1828,Tseng Noodles,Scallion With Sichuan Pepper Flavor,Pack,Taiwan,5.00,2016 #9,500
891,1689,Wugudaochang,Tomato Beef Brisket Flavor Purple Potato Noodle,Pack,China,5.00,2016 #7,500
942,1638,A-Sha Dry Noodle,Veggie Noodle Tomato Noodle With Vine Ripened ...,Pack,Taiwan,5.00,2015 #10,500
963,1617,MyKuali,Penang Hokkien Prawn Noodle (New Improved Taste),Pack,Malaysia,5.00,2015 #7,500
995,1585,CarJEN,Nyonya Curry Laksa,Pack,Malaysia,5.00,2015 #4,500
1059,1521,Maruchan,Gotsumori Sauce Yakisoba,Tray,Japan,5.00,2015 #9,500
1072,1508,Mamee,Chef Gold Recipe Mi Kari Seribu Rasa,Pack,Malaysia,5.00,2015 #6,500
1080,1500,MyKuali,Penang Red Tom Yum Goong Noodle,Pack,Malaysia,5.00,2015 #1,500
1109,1471,Mama,Instant Noodles Shrimp Creamy Tom Yum Flavour ...,Pack,Thailand,5.00,2013 #10,500
1114,1466,Mama,Oriental Style Instant Noodles Green Curry Fla...,Pack,Thailand,5.00,2015 #8,500
1230,1350,Mamee,Chef Curry Laksa Flavour,Pack,Malaysia,5.00,2014 #7,500
1250,1330,Sapporo Ichiban,Otafuku Okonomi Sauce Yakisoba,Tray,Japan,5.00,2014 #4,500
1272,1308,Nongshim,Soon Veggie Noodle Soup,Pack,South Korea,5.00,2014 #9,500
1278,1302,Mama,Instant Noodles Yentafo Tom Yum Mohfai Flavour,Pack,Thailand,5.00,2014 #10,500
1309,1271,Prima Taste,Singapore Chilli Crab La Mian,Pack,Singapore,5.00,2014 #8,500
1382,1198,Samyang Foods,Maesaengyitangmyun Baked Noodle,Pack,South Korea,5.00,2014 #5,500
1397,1183,Paldo,Cheese Noodle,Pack,South Korea,5.00,2014 #6,500
1493,1087,MyKuali,Penang White Curry Noodle,Pack,Malaysia,5.00,2014 #1,500
1588,992,Prima Taste,Singapore Laksa La Mian,Pack,Singapore,5.00,2013 #1,500
1589,991,Prima Taste,Singapore Curry La Mian,Pack,Singapore,5.00,2013 #2,500
1646,934,Nongshim,Jinjja Jinjja Flamin' Hot & Nutty,Pack,USA,5.00,2013 #4,500
1757,823,Paldo,Kokomen Spicy Chicken,Pack,South Korea,5.00,2013 #9,500
1865,715,Indomie,Mi Goreng Rendang (Import),Pack,Indonesia,5.00,2013 #3,500
1972,608,Koka,Spicy Black Pepper,Pack,Singapore,5.00,2012 #10,500
2002,578,Nongshim,Shin Ramyun Black,Pack,South Korea,4.75,2012 #7,500
2146,434,Mi Sedaap,Kari Spesial,Pack,Indonesia,4.50,2012 #5,500
2188,392,Nissin,Yakisoba Noodles Karashi,Tray,Japan,5.00,2012 #3,500
2189,391,Myojo,Hyoubanya No Chukasoba Oriental,Pack,Japan,4.25,2012 #6,500
2295,285,Doll,Artificial Chicken,Pack,Hong Kong,4.50,2012 #9,500
2475,105,Indomie,Special Fried Curly Noodle,Pack,Indonesia,5.00,2012 #1,500
2533,47,Indomie,Mi Goreng Jumbo Barbecue Chicken,Pack,Indonesia,5.00,2012 #2,500
2549,31,Myojo,Ippeichan Yakisoba,Tray,Japan,4.00,2013 #6,500
2567,13,Sapporo Ichiban,Chow Mein,Pack,Japan,5.00,2012 #4,500

In [16]:
#calculate Ramen Score by  ('Review #'/(3.65 * 1.5)) * 'Stars' + 'Top Ten - extra pts'
#dividing the Review number by 3.65 will scale down the weight of number of reviews that goes into calculating the ramen score.
#3.65 was choosen because that is mean/avg stars in the data set
#After using 3.65 as the divider to scale down, It still rewarded and weight Review # too much or too highly
#We are going to divide Review # by 5.475 instead. We got 5.475 from multiplying 3.65 by 1.5

ramen_df['Ramen Score'] = ((ramen_df['Review #'] / (3.65*1.5)) *  ramen_df['Stars'] + ramen_df['Top Ten - extra pts'])

display(ramen_df.head())

print('\n')

#get summary statistics of Ramen Score
display(ramen_df['Ramen Score'].describe())

print('\n')

#check the scores of Top Ten awarded Ramen
display(ramen_df[ramen_df['Top Ten'] != 'no'])

#This shows most of the top 10 awarded Ramen are above the mean Ramen Score.
#While the scoring system isn't perfect, it is a good way to

,Review #,Brand,Variety,Style,Country,Stars,Top Ten,Top Ten - extra pts,Ramen Score
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,no,0,1767.123288
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1.00,no,0,471.050228
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,no,0,1059.452055
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,no,0,1294.383562
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,no,0,1764.383562

count    2580.000000
mean      900.470850
std       616.942796
min         0.000000
25%       362.945205
50%       821.347032
75%      1372.191781
max      2347.031963
Name: Ramen Score, dtype: float64

,Review #,Brand,Variety,Style,Country,Stars,Top Ten,Top Ten - extra pts,Ramen Score
616,1964,MAMA,Instant Noodles Coconut Milk Flavour,Pack,Myanmar,5.00,2016 #10,500,2293.607306
633,1947,Prima Taste,Singapore Laksa Wholegrain La Mian,Pack,Singapore,5.00,2016 #1,500,2278.082192
655,1925,Prima,Juzz's Mee Creamy Chicken Flavour,Pack,Singapore,5.00,2016 #8,500,2257.990868
673,1907,Prima Taste,Singapore Curry Wholegrain La Mian,Pack,Singapore,5.00,2016 #5,500,2241.552511
752,1828,Tseng Noodles,Scallion With Sichuan Pepper Flavor,Pack,Taiwan,5.00,2016 #9,500,2169.406393
891,1689,Wugudaochang,Tomato Beef Brisket Flavor Purple Potato Noodle,Pack,China,5.00,2016 #7,500,2042.465753
942,1638,A-Sha Dry Noodle,Veggie Noodle Tomato Noodle With Vine Ripened ...,Pack,Taiwan,5.00,2015 #10,500,1995.890411
963,1617,MyKuali,Penang Hokkien Prawn Noodle (New Improved Taste),Pack,Malaysia,5.00,2015 #7,500,1976.712329
995,1585,CarJEN,Nyonya Curry Laksa,Pack,Malaysia,5.00,2015 #4,500,1947.488584
1059,1521,Maruchan,Gotsumori Sauce Yakisoba,Tray,Japan,5.00,2015 #9,500,1889.041096
1072,1508,Mamee,Chef Gold Recipe Mi Kari Seribu Rasa,Pack,Malaysia,5.00,2015 #6,500,1877.168950
1080,1500,MyKuali,Penang Red Tom Yum Goong Noodle,Pack,Malaysia,5.00,2015 #1,500,1869.863014
1109,1471,Mama,Instant Noodles Shrimp Creamy Tom Yum Flavour ...,Pack,Thailand,5.00,2013 #10,500,1843.378995
1114,1466,Mama,Oriental Style Instant Noodles Green Curry Fla...,Pack,Thailand,5.00,2015 #8,500,1838.812785
1230,1350,Mamee,Chef Curry Laksa Flavour,Pack,Malaysia,5.00,2014 #7,500,1732.876712
1250,1330,Sapporo Ichiban,Otafuku Okonomi Sauce Yakisoba,Tray,Japan,5.00,2014 #4,500,1714.611872
1272,1308,Nongshim,Soon Veggie Noodle Soup,Pack,South Korea,5.00,2014 #9,500,1694.520548
1278,1302,Mama,Instant Noodles Yentafo Tom Yum Mohfai Flavour,Pack,Thailand,5.00,2014 #10,500,1689.041096
1309,1271,Prima Taste,Singapore Chilli Crab La Mian,Pack,Singapore,5.00,2014 #8,500,1660.730594
1382,1198,Samyang Foods,Maesaengyitangmyun Baked Noodle,Pack,South Korea,5.00,2014 #5,500,1594.063927
1397,1183,Paldo,Cheese Noodle,Pack,South Korea,5.00,2014 #6,500,1580.365297
1493,1087,MyKuali,Penang White Curry Noodle,Pack,Malaysia,5.00,2014 #1,500,1492.694064
1588,992,Prima Taste,Singapore Laksa La Mian,Pack,Singapore,5.00,2013 #1,500,1405.936073
1589,991,Prima Taste,Singapore Curry La Mian,Pack,Singapore,5.00,2013 #2,500,1405.022831
1646,934,Nongshim,Jinjja Jinjja Flamin' Hot & Nutty,Pack,USA,5.00,2013 #4,500,1352.968037
1757,823,Paldo,Kokomen Spicy Chicken,Pack,South Korea,5.00,2013 #9,500,1251.598174
1865,715,Indomie,Mi Goreng Rendang (Import),Pack,Indonesia,5.00,2013 #3,500,1152.968037
1972,608,Koka,Spicy Black Pepper,Pack,Singapore,5.00,2012 #10,500,1055.251142
2002,578,Nongshim,Shin Ramyun Black,Pack,South Korea,4.75,2012 #7,500,1001.461187
2146,434,Mi Sedaap,Kari Spesial,Pack,Indonesia,4.50,2012 #5,500,856.712329
2188,392,Nissin,Yakisoba Noodles Karashi,Tray,Japan,5.00,2012 #3,500,857.990868
2189,391,Myojo,Hyoubanya No Chukasoba Oriental,Pack,Japan,4.25,2012 #6,500,803.515982
2295,285,Doll,Artificial Chicken,Pack,Hong Kong,4.50,2012 #9,500,734.246575
2475,105,Indomie,Special Fried Curly Noodle,Pack,Indonesia,5.00,2012 #1,500,595.890411
2533,47,Indomie,Mi Goreng Jumbo Barbecue Chicken,Pack,Indonesia,5.00,2012 #2,500,542.922374
2549,31,Myojo,Ippeichan Yakisoba,Tray,Japan,4.00,2013 #6,500,522.648402
2567,13,Sapporo Ichiban,Chow Mein,Pack,Japan,5.00,2012 #4,500,511.872146

In [17]:
#Overall Mean Ramen Score by Country
Avg_Ramen_by_country = ramen_df.groupby(['Country']).mean('Ramen Score').sort_values(by = 'Ramen Score', ascending = False, inplace= False)
display(Avg_Ramen_by_country)

                  Review #     Stars  Top Ten - extra pts  Ramen Score
Country
Brazil         2093.600000  4.350000             0.000000  1660.593607
Ghana          2545.000000  3.500000             0.000000  1626.940639
Mexico         2275.160000  3.730000             0.000000  1550.748858
Cambodia       1822.400000  4.200000             0.000000  1393.990868
Myanmar        1879.000000  3.946429            35.714286  1388.467058
Germany        2055.518519  3.638889             0.000000  1379.428378
United States  2007.000000  3.750000             0.000000  1374.657534
Sarawak        1707.333333  4.333333             0.000000  1350.684932
Singapore      1702.917431  4.126147            32.110092  1341.356458
Bangladesh     1953.857143  3.714286             0.000000  1332.883235
Hungary        1929.777778  3.611111             0.000000  1271.410452
Malaysia       1623.602564  4.127571            19.230769  1264.050857
Hong Kong      1693.423358  3.801825             3.649635  1223.827284
Finland        1797.666667  3.583333             0.000000  1176.042618
Australia      2005.000000  3.138636             0.000000  1154.158157
Fiji           1644.500000  3.875000             0.000000  1129.668950
India          1522.225806  3.395161             0.000000  1034.234792
Japan          1375.928977  3.981605             8.522727  1029.176707
Taiwan         1296.339286  3.665402             4.464286   929.186848
Sweden         1519.333333  3.250000             0.000000   901.324201
Pakistan       1672.666667  3.000000             0.000000   895.981735
China          1327.189349  3.421893             2.958580   868.954095
Netherlands    1866.000000  2.483333             0.000000   838.121766
Thailand       1141.120419  3.384817             7.853403   779.483660
Colombia       1265.500000  3.291667             0.000000   760.456621
Nepal          1223.071429  3.553571             0.000000   757.302674
Indonesia       991.484127  4.067460            15.873016   750.462782
South Korea    1013.566343  3.766026             8.090615   733.336440
USA            1086.730650  3.457043             1.547988   711.506991
Estonia        1099.500000  3.500000             0.000000   702.899543
Nigeria        2502.000000  1.500000             0.000000   685.479452
UK             1217.797101  2.997101             0.000000   668.623652
Poland          972.000000  3.625000             0.000000   644.006849
Canada         1361.512195  2.243902             0.000000   584.735494
Holland         769.250000  3.562500             0.000000   497.785388
Vietnam         858.870370  3.187963             0.000000   495.157872
Dubai           753.000000  3.583333             0.000000   493.165906
Philippines     613.893617  3.329787             0.000000   406.923152

In [18]:
#sort by top 1000 Ramen Scores and create a new df for Top 1000 Ramen
Top_Ramen = ramen_df.sort_values(by = 'Ramen Score', ascending = False, inplace= False).head(1000)

display(Top_Ramen)

#From the top 1000 Ramen Scores, we can get more insight to our questions

,Review #,Brand,Variety,Style,Country,Stars,Top Ten,Top Ten - extra pts,Ramen Score
10,2570,Tao Kae Noi,Creamy tom Yum Kung Flavour,Pack,Thailand,5.00,no,0,2347.031963
11,2569,Yamachan,Yokohama Tonkotsu Shoyu,Pack,USA,5.00,no,0,2346.118721
14,2566,Nissin,Demae Ramen Bar Noodle Aka Tonkotsu Flavour In...,Pack,Hong Kong,5.00,no,0,2343.378995
17,2563,Yamachan,Tokyo Shoyu Ramen,Pack,USA,5.00,no,0,2340.639269
21,2559,Jackpot Teriyaki,Beef Ramen,Pack,USA,5.00,no,0,2336.986301
...,...,...,...,...,...,...,...,...,...
947,1633,A-One,Mi Ly Instant Noodles Mi Bo Beef Flavor,Cup,Vietnam,3.50,no,0,1043.926941
676,1904,Bonasia,Instant Noodles Duck Flavour,Pack,Hungary,3.00,no,0,1043.287671
823,1757,iMee,Instant Noodles Beef Flavour,Pack,Netherlands,3.25,no,0,1042.968037
1154,1426,Ottogi,Cheese Bokki,Bowl,South Korea,4.00,no,0,1041.826484
951,1629,Hao Way,Penang Laksa Instant Bowl Noodles,Bowl,Malaysia,3.50,no,0,1041.369863

In [19]:
#Top 1000 Mean Ramen Score by Country
Top_avg_Ramen_by_country = Top_Ramen.groupby(['Country']).mean('Ramen Score').sort_values(by = 'Ramen Score', ascending = False, inplace= False).head(50)
display(Top_avg_Ramen_by_country)

                  Review #     Stars  Top Ten - extra pts  Ramen Score
Country
Hong Kong      2199.268293  4.198780             0.000000  1686.218733
Singapore      2036.626667  4.396667            46.666667  1676.797565
Brazil         2093.600000  4.350000             0.000000  1660.593607
Taiwan         2030.643678  4.449425            11.494253  1657.249777
India          2223.714286  4.053571             0.000000  1652.677756
South Korea    2034.576923  4.381410            25.641026  1644.566795
Japan          2040.540881  4.405031             6.289308  1637.991270
Ghana          2545.000000  3.500000             0.000000  1626.940639
Germany        2325.210526  3.736842             0.000000  1591.540495
Fiji           2391.000000  3.625000             0.000000  1582.739726
Mexico         2275.160000  3.730000             0.000000  1550.748858
USA            2057.582278  4.088608             6.329114  1533.046645
Indonesia      1867.952381  4.369048            23.809524  1488.360513
Malaysia       1769.805556  4.506944            27.777778  1488.332911
China          1949.382353  4.117647             7.352941  1471.197959
Myanmar        1876.916667  4.145833            41.666667  1461.533486
UK             2012.416667  3.983333             0.000000  1451.237443
Australia      2188.571429  3.592857             0.000000  1432.336595
Thailand       1914.400000  4.030000            20.000000  1419.532420
Pakistan       2201.500000  3.500000             0.000000  1408.127854
Cambodia       1822.400000  4.200000             0.000000  1393.990868
Bangladesh     1997.500000  3.791667             0.000000  1387.633181
Vietnam        1991.272727  3.772727             0.000000  1379.738481
United States  2007.000000  3.750000             0.000000  1374.657534
Sarawak        1707.333333  4.333333             0.000000  1350.684932
Hungary        1937.250000  3.718750             0.000000  1312.928082
Canada         1926.300000  3.700000             0.000000  1270.000000
Netherlands    1837.166667  3.541667             0.000000  1184.771689
Finland        1797.666667  3.583333             0.000000  1176.042618
Philippines    1553.875000  4.031250             0.000000  1143.333333

In [20]:
#What're the top 10 best rated ramens?
Top_10_Ramen = ramen_df.sort_values(by = 'Ramen Score', ascending = False, inplace= False).head(10)

display(Top_10_Ramen)

,Review #,Brand,Variety,Style,Country,Stars,Top Ten,Top Ten - extra pts,Ramen Score
10,2570,Tao Kae Noi,Creamy tom Yum Kung Flavour,Pack,Thailand,5.0,no,0,2347.031963
11,2569,Yamachan,Yokohama Tonkotsu Shoyu,Pack,USA,5.0,no,0,2346.118721
14,2566,Nissin,Demae Ramen Bar Noodle Aka Tonkotsu Flavour In...,Pack,Hong Kong,5.0,no,0,2343.378995
17,2563,Yamachan,Tokyo Shoyu Ramen,Pack,USA,5.0,no,0,2340.639269
21,2559,Jackpot Teriyaki,Beef Ramen,Pack,USA,5.0,no,0,2336.986301
22,2558,KOKA,Creamy Soup With Crushed Noodles Hot & Sour Fi...,Cup,Singapore,5.0,no,0,2336.073059
28,2552,MyKuali,Penang White Curry Rice Vermicelli Soup,Bowl,Malaysia,5.0,no,0,2330.593607
30,2550,Samyang Foods,Paegaejang Ramen,Pack,South Korea,5.0,no,0,2328.767123
35,2545,KOKA,Instant Noodles Laksa Singapura Flavour,Pack,Singapore,5.0,no,0,2324.200913
37,2543,KOKA,Curry Flavour Instant Noodles,Cup,Singapore,5.0,no,0,2322.374429

In [21]:
#How many of the top 1000 Ramen are from each country?

top_country = Top_Ramen['Country'].value_counts()

print(top_country)

Japan            159
Malaysia         108
Taiwan            87
Hong Kong         82
USA               79
South Korea       78
Singapore         75
Thailand          75
China             68
Mexico            25
Indonesia         21
Germany           19
India             14
Australia         14
UK                12
Myanmar           12
Vietnam           11
Canada            10
Philippines        8
Hungary            8
Bangladesh         6
Netherlands        6
Cambodia           5
Brazil             5
Finland            3
Sarawak            3
Ghana              2
Pakistan           2
Fiji               2
United States      1
Name: Country, dtype: int64

In [22]:
#Which style of ramen was most popular or best rated? 
top_style = Top_Ramen['Style'].value_counts()
print(top_style)

Pack    576
Cup     222
Bowl    176
Tray     20
Box       4
Can       1
Bar       1
Name: Style, dtype: int64

In [23]:
#Pull the top Ramen Score by each country
Top_Ramen_by_country = Top_Ramen.groupby(['Country']).max('Ramen Score').sort_values(by = 'Ramen Score', ascending = False, inplace= False).head(50)
display(Top_Ramen_by_country)
print('\n')

#the group by doesn't display which Brand and Variety the top Ramen scores from each country belong to

#Create list of Top Ramen Scores to be used as filter on to see which Brand and Variety does the scores belong to
filter_score_list = []
for score in Top_Ramen_by_country["Ramen Score"]:
    filter_score_list.append(score)


print(filter_score_list)
print('\n')

#filter on our Top_Ramen df based on the top scores 
#Top_Ramen_filtered_by_country = Top_Ramen[Top_Ramen['Ramen Score'].isin(filter_score_list)]
#display(Top_Ramen_filtered_by_country)

               Review #  Stars  Top Ten - extra pts  Ramen Score
Country
Thailand           2570   5.00                  500  2347.031963
USA                2578   5.00                  500  2346.118721
Hong Kong          2566   5.00                    0  2343.378995
Singapore          2571   5.00                  500  2336.073059
Malaysia           2552   5.00                  500  2330.593607
South Korea        2575   5.00                  500  2328.767123
Japan              2580   5.00                  500  2303.196347
Taiwan             2577   5.00                  500  2296.803653
Myanmar            2010   5.00                  500  2293.607306
Germany            2498   5.00                    0  2274.885845
Indonesia          2549   5.00                  500  2226.484018
China              2547   5.00                  500  2192.694064
Vietnam            2562   5.00                    0  2149.771689
Mexico             2442   5.00                    0  2132.420091
India              2576   5.00                    0  2126.940639
UK                 2200   5.00                    0  2009.132420
Australia          2349   5.00                    0  1888.584475
Brazil             2204   5.00                    0  1863.013699
Fiji               2396   4.00                    0  1743.196347
Hungary            2492   4.75                    0  1706.849315
Bangladesh         2325   4.00                    0  1698.630137
Cambodia           1929   5.00                    0  1697.716895
Ghana              2554   3.50                    0  1632.694064
Pakistan           2210   4.00                    0  1614.611872
Sarawak            1717   5.00                    0  1549.771689
Canada             2242   5.00                    0  1514.520548
Netherlands        2009   4.50                    0  1465.479452
United States      2007   3.75                    0  1374.657534
Philippines        1645   4.50                    0  1259.178082
Finland            1905   3.75                    0  1217.808219

[2347.03196347032, 2346.1187214611873, 2343.3789954337904, 2336.0730593607304, 2330.593607305936, 2328.7671232876714, 2303.1963470319633, 2296.8036529680367, 2293.6073059360733, 2274.8858447488587, 2226.4840182648404, 2192.6940639269405, 2149.771689497717, 2132.420091324201, 2126.9406392694063, 2009.1324200913243, 1888.5844748858449, 1863.0136986301372, 1743.1963470319636, 1706.849315068493, 1698.6301369863015, 1697.716894977169, 1632.6940639269405, 1614.611872146119, 1549.771689497717, 1514.5205479452056, 1465.4794520547946, 1374.6575342465756, 1259.178082191781, 1217.8082191780823]

In [24]:
#filter on our Top_Ramen df based on the top scores from each country 
Top_Ramen_filtered_by_country = Top_Ramen[Top_Ramen['Ramen Score'].isin(filter_score_list)]
display(Top_Ramen_filtered_by_country)

,Review #,Brand,Variety,Style,Country,Stars,Top Ten,Top Ten - extra pts,Ramen Score
10,2570,Tao Kae Noi,Creamy tom Yum Kung Flavour,Pack,Thailand,5.00,no,0,2347.031963
11,2569,Yamachan,Yokohama Tonkotsu Shoyu,Pack,USA,5.00,no,0,2346.118721
14,2566,Nissin,Demae Ramen Bar Noodle Aka Tonkotsu Flavour In...,Pack,Hong Kong,5.00,no,0,2343.378995
22,2558,KOKA,Creamy Soup With Crushed Noodles Hot & Sour Fi...,Cup,Singapore,5.00,no,0,2336.073059
28,2552,MyKuali,Penang White Curry Rice Vermicelli Soup,Bowl,Malaysia,5.00,no,0,2330.593607
30,2550,Samyang Foods,Paegaejang Ramen,Pack,South Korea,5.00,no,0,2328.767123
58,2522,Takamori,Hearty Japanese Style Curry Udon,Pack,Japan,5.00,no,0,2303.196347
65,2515,Uni-President,Man Han Feast Spicy Beef Flavor Instant Noodles,Bowl,Taiwan,5.00,no,0,2296.803653
616,1964,MAMA,Instant Noodles Coconut Milk Flavour,Pack,Myanmar,5.00,2016 #10,500,2293.607306
89,2491,Nissin,Soba Yakitori Chicken,Cup,Germany,5.00,no,0,2274.885845
142,2438,World O' Noodle,Mi Goreng Original Flavour Fried Noodles,Pack,Indonesia,5.00,no,0,2226.484018
179,2401,Sichuan Baijia,Chongqing Noodles Burning Dry Noodles,Bowl,China,5.00,no,0,2192.694064
226,2354,Vifon,Viet Cuisine Bun Rieu Cua Sour Crab Soup Insta...,Bowl,Vietnam,5.00,no,0,2149.771689
245,2335,Nissin,Cup Noodles Gourmet Sabor A Caldo De Camaron,Cup,Mexico,5.00,no,0,2132.420091
251,2329,Patanjali,Atta Noodles Jhatpat Banao Befikr Khao,Pack,India,5.00,no,0,2126.940639
380,2200,Mr. Lee's Noodles,Shaolin Monk Vegetables,Cup,UK,5.00,no,0,2009.132420
512,2068,Maggi,Fusian Special Edition Ow... Ow... Spicy Cow M...,Pack,Australia,5.00,no,0,1888.584475
540,2040,Nissin,Cup Noodles Sabor Franhp Com Requeijao,Cup,Brazil,5.00,no,0,1863.013699
194,2386,Maggi,2 Minute Noodles Curry Flavour,Pack,Fiji,4.00,no,0,1743.196347
88,2492,Nissin,Smack Chili,Pack,Hungary,3.75,no,0,1706.849315
255,2325,Pran,Mr. Noodles Curry Flavor Instant Noodles,Pack,Bangladesh,4.00,no,0,1698.630137
721,1859,Mama,Instant Noodles chicken Green Curry Flavour,Pack,Cambodia,5.00,no,0,1697.716895
26,2554,Yum-Mie,Instant Noodles Beef In Light Soup Flavour,Pack,Ghana,3.50,no,0,1632.694064
370,2210,Morre,Instant Noodles Masala,Pack,Pakistan,4.00,no,0,1614.611872
883,1697,The Kitchen Food,Instant Kampua Dark Soy Sauce,Pack,Sarawak,5.00,no,0,1549.771689
507,2073,Great Value,Spicy Ramen Noodles,Pack,Canada,4.00,no,0,1514.520548
797,1783,iMee,Instant Noodles Creamy Tom Yum Shrimp Flavour,Pack,Netherlands,4.50,no,0,1465.479452
573,2007,Nongshim,Rice Fettucini Alfredo,Pack,United States,3.75,no,0,1374.657534
1048,1532,Lucky Me!,Special Instant Noodles Jjamppong Flavor,Pack,Philippines,4.50,no,0,1259.178082
675,1905,Pirkka,Nuudeli Kana Nudlar Kyckling,Pack,Finland,3.50,no,0,1217.808219